---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: updatey
  labels:
    app: updatey
webhooks:
  - name: updatey.jw-s.com
    clientConfig:
      service:
        name: updatey
        namespace: updatey
        path: "/admit"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ2ekNDQXRPZ0F3SUJBZ0lKQUs3dHFGNlNSVGVvTUEwR0NTcUdTSWIzRFFFQkN3VUFNSUdWTVFzd0NRWUQKVlFRR0V3SkVSVEVRTUE0R0ExVUVDQXdIUW1GMllYSnBZVEVYTUJVR0ExVUVCd3dPU0dWeWVtOW5aVzVoZFhKaApZMmd4RHpBTkJnTlZCQW9NQm1Ga2FXUmhjekVOTUFzR0ExVUVDd3dFVUVVbVFURWRNQnNHQ1NxR1NJYjNEUUVKCkFSWU9iMlJ3UUdGa2FXUmhjeTVqYjIweEhEQWFCZ05WQkFNTUUzVndaR0YwWlhrdWRYQmtZWFJsZVM1emRtTXcKSGhjTk1Ua3dNekV6TVRNMU1ESXdXaGNOTWpFd016RXlNVE0xTURJd1dqQ0JsVEVMTUFrR0ExVUVCaE1DUkVVeApFREFPQmdOVkJBZ01CMEpoZG1GeWFXRXhGekFWQmdOVkJBY01Ea2hsY25wdloyVnVZWFZ5WVdOb01ROHdEUVlEClZRUUtEQVpoWkdsa1lYTXhEVEFMQmdOVkJBc01CRkJGSmtFeEhUQWJCZ2txaGtpRzl3MEJDUUVXRG05a2NFQmgKWkdsa1lYTXVZMjl0TVJ3d0dnWURWUVFEREJOMWNHUmhkR1Y1TG5Wd1pHRjBaWGt1YzNaak1JSUJJakFOQmdrcQpoa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXpUWm1RNHd0bHVLakpqMk1tcElWNWxhQkIrZGxFd2xiCko2RXdiQS9JcC9PcTRRT3JXeXN3bUFJUE15QVRaNm5ncDJ5bktNWE5xZmt2bG95ODhRNVdJbGRkWGFROUJHZGsKRStjMG84bTZQekhTQjg3a3ljSThsWGdvVGVOZk01WmFYc2xyNjlOWW1TVDNpOWs4T21ZWGlkM3Z3V1RCZ1lNVwp1c05LbGs5ekErWFIwb0Y1N1J1TjhHWWY5ZU1WYlk3V2E4SmRVTXp6TEN1dUY0Sm1mVkh5bitFcVhMaGJQTmE2Cm93ajVjeG1VamE4cGNHMXZ6Vng5M3hPUTg5bXUyNXZNVHNFWFdFbnVEWUlBQTVweUlOWElCUGpoTEN0NFBMUkkKaHVhSUY1aGZ4c3FpQ0c0ZzlOQkFhOW9FTXBxZWRnN1pkMmtzb3N0cW9WMjRXeEJNNlNodDR3SURBUUFCb3p3dwpPakE0QmdOVkhSRUVNVEF2Z2dkMWNHUmhkR1Y1Z2c5MWNHUmhkR1Y1TG5Wd1pHRjBaWG1DRTNWd1pHRjBaWGt1CmRYQmtZWFJsZVM1emRtTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBS0hHY1VVaU8vU2F4N1VXcEVPTEI1VlEKWGg2YXFoaUh1eEphWU9CRkMyM29PVDM4QzdjYWtUd05wcVN2UDJ0SlBxcFk2RUJHUDZ5N25QY3k5NE85UVlKdwpMUDBRVStRdEh6MXIvUWtxZFo0ajdRMnRQNTRsS1IwWENiWWJRQmI3c3JIc0E1MUZUYnlvdVNRNG8rRXNJQ2lICnZ1SG90cDlPTUZHYzBWYWRKMXNMOHBEQjh1Wk5EcE9ZOGZVbjVUd3NHbW0zcDFHSEl4L0Q0SUFYZTVYVG1jaG8KV3FmQUdudmVIVFhKMzIwSUV3UFFqZURJU21rNkpmc2VVaGtybngrQmxLdG1FOXMvS2QxUnB0Mm9nZksycHN0Nwprem01Umx1TU1xSldlbDRYaUg3MndwcWtoanJ6QnFwQStWdmx1MW5KK0NPY1M0RVUrRHIzeGVFejg3aE1LcWM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*"]
    failurePolicy: Ignore