
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: updatey
  labels:
    app: {{ template "updatey.name" . }}
    chart: {{ template "updatey.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]