apiVersion: v1
kind: Service
metadata:
  name: {{ template "updatey.name" . }}
  labels:
    app: {{ template "updatey.name" . }}
    chart: {{ template "updatey.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ template "updatey.name" . }}
    release: {{ .Release.Name }}
